/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Tech Blog",
  "description": "Notes written by BenThomson when learning tech skills.",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "简介",
      "frontmatter": {
        "permalink": "d3js-introduction",
        "type": "series",
        "series": "Getting started with d3.js"
      },
      "regularPath": "/data/data-vis/D3/%E7%AE%80%E4%BB%8B.html",
      "relativePath": "data/data-vis/D3/简介.md",
      "key": "v-057e6eb2",
      "path": "/d3js-introduction/",
      "headers": [
        {
          "level": 2,
          "title": "下载安装",
          "slug": "下载安装"
        }
      ],
      "lastUpdateTime": "2021-02-07"
    },
    {
      "title": "SVG",
      "frontmatter": {},
      "regularPath": "/data/data-vis/D3/SVG.html",
      "relativePath": "data/data-vis/D3/SVG.md",
      "key": "v-679d6378",
      "path": "/data/data-vis/D3/SVG.html",
      "headers": [
        {
          "level": 2,
          "title": "坐标定位",
          "slug": "坐标定位"
        },
        {
          "level": 2,
          "title": "viewport 和 viewBox",
          "slug": "viewport-和-viewbox"
        },
        {
          "level": 2,
          "title": "基本形状",
          "slug": "基本形状"
        },
        {
          "level": 3,
          "title": "矩形和圆角矩形",
          "slug": "矩形和圆角矩形"
        },
        {
          "level": 3,
          "title": "圆形和椭圆",
          "slug": "圆形和椭圆"
        },
        {
          "level": 3,
          "title": "线条和折线",
          "slug": "线条和折线"
        },
        {
          "level": 3,
          "title": "多边形",
          "slug": "多边形"
        },
        {
          "level": 2,
          "title": "路径",
          "slug": "路径"
        },
        {
          "level": 3,
          "title": "直线",
          "slug": "直线"
        },
        {
          "level": 3,
          "title": "曲线",
          "slug": "曲线"
        },
        {
          "level": 2,
          "title": "文本",
          "slug": "文本"
        },
        {
          "level": 2,
          "title": "工具",
          "slug": "工具"
        },
        {
          "level": 2,
          "title": "资源",
          "slug": "资源"
        }
      ],
      "lastUpdateTime": "2021-02-07"
    },
    {
      "title": "基础操作",
      "frontmatter": {},
      "regularPath": "/data/data-vis/D3/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html",
      "relativePath": "data/data-vis/D3/基础操作.md",
      "key": "v-7cf560fa",
      "path": "/data/data-vis/D3/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C.html",
      "headers": [
        {
          "level": 2,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 2,
          "title": "动态属性",
          "slug": "动态属性"
        },
        {
          "level": 2,
          "title": "enter 和 exit",
          "slug": "enter-和-exit"
        },
        {
          "level": 2,
          "title": "D3 不是一种新的表示方法",
          "slug": "d3-不是一种新的表示方法"
        },
        {
          "level": 2,
          "title": "过渡",
          "slug": "过渡"
        }
      ],
      "lastUpdateTime": "2021-02-07"
    },
    {
      "title": "Home",
      "frontmatter": {
        "layout": "HomeLayout",
        "title": "Home",
        "cards": [
          {
            "name": "Data",
            "tags": [
              "数据分析",
              "数据可视化"
            ],
            "bg": "img/home/data.svg"
          },
          {
            "name": "Web",
            "tags": [
              "前端开发",
              "后端开发"
            ],
            "bg": "img/home/web.svg"
          },
          {
            "name": "Design",
            "tags": [
              "平面设计",
              "插画",
              "人机交互"
            ],
            "bg": "img/home/design.svg"
          },
          {
            "name": "Other",
            "tags": [
              "Git"
            ],
            "bg": "img/home/other.svg"
          },
          {
            "name": "Toolbox",
            "tags": [
              "Design"
            ],
            "bg": "img/home/toolbox.svg"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-50dc5f6e",
      "path": "/",
      "lastUpdated": "2/4/2021, 2:49:18 PM",
      "lastUpdateTime": "2021-02-07"
    },
    {
      "title": "demo",
      "frontmatter": {
        "date": "2021-02-05T00:00:00.000Z"
      },
      "regularPath": "/test.html",
      "relativePath": "test.md",
      "key": "v-e902cc16",
      "path": "/test.html",
      "headers": [
        {
          "level": 2,
          "title": "heading",
          "slug": "heading"
        },
        {
          "level": 2,
          "title": "h2 Heading",
          "slug": "h2-heading"
        },
        {
          "level": 3,
          "title": "h3 Heading",
          "slug": "h3-heading"
        },
        {
          "level": 2,
          "title": "Horizontal Rules",
          "slug": "horizontal-rules"
        },
        {
          "level": 2,
          "title": "Emphasis",
          "slug": "emphasis"
        },
        {
          "level": 2,
          "title": "Blockquotes",
          "slug": "blockquotes"
        },
        {
          "level": 2,
          "title": "Lists",
          "slug": "lists"
        },
        {
          "level": 2,
          "title": "Code",
          "slug": "code"
        },
        {
          "level": 2,
          "title": "Tables",
          "slug": "tables"
        },
        {
          "level": 2,
          "title": "Links",
          "slug": "links"
        },
        {
          "level": 2,
          "title": "Emojies",
          "slug": "emojies"
        },
        {
          "level": 2,
          "title": "Subscript",
          "slug": "subscript"
        },
        {
          "level": 2,
          "title": "Footnotes",
          "slug": "footnotes"
        },
        {
          "level": 2,
          "title": "Custom containers",
          "slug": "custom-containers"
        }
      ],
      "lastUpdateTime": "2021-02-07"
    },
    {
      "title": "CSS3",
      "frontmatter": {
        "tags": [
          "css"
        ],
        "date": "2021-02-05T00:00:00.000Z",
        "author": "BenThomson"
      },
      "regularPath": "/web/CSS/CSS3.html",
      "relativePath": "web/CSS/CSS3.md",
      "key": "v-1055395e",
      "path": "/web/CSS/CSS3.html",
      "headers": [
        {
          "level": 2,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "基础选择器",
          "slug": "基础选择器"
        },
        {
          "level": 3,
          "title": "结构选择器",
          "slug": "结构选择器"
        },
        {
          "level": 3,
          "title": "否定选择器",
          "slug": "否定选择器"
        },
        {
          "level": 3,
          "title": "属性选择器",
          "slug": "属性选择器"
        },
        {
          "level": 3,
          "title": "伪类选择器",
          "slug": "伪类选择器"
        },
        {
          "level": 3,
          "title": "伪元素",
          "slug": "伪元素"
        },
        {
          "level": 2,
          "title": "背景",
          "slug": "背景"
        },
        {
          "level": 3,
          "title": "背景图",
          "slug": "背景图"
        },
        {
          "level": 3,
          "title": "背景颜色渐变",
          "slug": "背景颜色渐变"
        },
        {
          "level": 2,
          "title": "文本",
          "slug": "文本"
        },
        {
          "level": 3,
          "title": "换行",
          "slug": "换行"
        },
        {
          "level": 3,
          "title": "对齐",
          "slug": "对齐"
        },
        {
          "level": 3,
          "title": "字体",
          "slug": "字体"
        },
        {
          "level": 2,
          "title": "获取网页字体",
          "slug": "获取网页字体"
        }
      ],
      "lastUpdateTime": "2021-02-07"
    },
    {
      "frontmatter": {
        "layout": "ListLayout"
      },
      "regularPath": "/web/",
      "key": "v-b15373a0",
      "path": "/web/",
      "lastUpdateTime": "2021-02-07"
    }
  ],
  "themeConfig": {
    "author": "BenThomson",
    "logo": "/img/Ben.png",
    "lastUpdated": true,
    "socialMedia": [
      {
        "name": "email",
        "logo": "/img/email.svg",
        "url": "mailto:mebeansbin@gmail.com"
      },
      {
        "name": "github",
        "logo": "/img/github.svg",
        "url": "https://github.com/Benbinbin"
      },
      {
        "name": "juejin",
        "logo": "/img/juejin.svg",
        "url": "https://juejin.cn/user/3175045314389278/posts"
      },
      {
        "name": "dribbble",
        "logo": "/img/dribbble.svg",
        "url": "https://dribbble.com/BinBinDesign"
      },
      {
        "name": "twitter",
        "logo": "/img/twitter.svg",
        "url": "https://twitter.com/Benbinbin_fun"
      },
      {
        "name": "weibo",
        "logo": "/img/weibo.svg",
        "url": "https://weibo.com/binbindesign"
      }
    ]
  }
}